### PR TITLE
add Monadless library

### PR DESCRIPTION
**Pull request by fwbrasil**

### CODE REVIEW

**Comment by fwbrasil** [comment]
the build seems to fail with an unrelated error

**Comment by ochrons** [comment]
The https-url doesn't have a valid certificate. Did you mean to use plain http?

**Comment by fwbrasil** [comment]
@ochrons fixed

**Comment by ochrons** [comment]
Can you also squash the commits into one ;)

**Comment by fwbrasil** [comment]
@ochrons done! :)

**Comment by fwbrasil** [comment]
@ochrons Thanks for merging the PR! I think I've missed something, it's returning this error:


```
ScalaFiddle.scala:-5: ERROR: Library io.monadless %%% monadless-core % 0.0.11 is not allowed
```

https://scalafiddle.io/sf/7YCMKer/1

**Pull request merged**
