### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mxl**
- added https://github.com/rtimush/sbt-updates plugin to easily check available dependency updates with `sbt dependencyUpdates`
- updated sbt to version `0.13.13`
- updated dependencies

Changes to `FiddleEditor.scala` and `Sidebar.scala` are caused by https://github.com/suzaku-io/diode/commit/4dc051281844b1df75847586fbc32a5d8131e838 commit.

### CODE REVIEW

**Comment by mxl** [comment]
@ochrons Should I update this PR to latest versions to get it merged?

**Comment by mxl** [comment]
@ochrons Sorry, could you pay some attention to this PR? I spent time to make and test it. If it's not useful anymore then please close it. If there is something that's not yet implemented on master branch then I can update it. The same concerns https://github.com/scalafiddle/scalafiddle-core/pull/16

**Comment by ochrons** [comment]
Sorry for leaving this hanging. I made a major update just past week, which got a bit more involved than just updating the dependencies (going to scalajs-react 1.0.0 for example). Typically I don't like to just update dependencies without any reason, as it may lead to some surprising bugs that surface later on.

I'll add the sbt-updates plugin and check what I might have missed, now that I'm still in the middle of a major update anyway :)

**Comment by ochrons** [comment]
For example updating Coursier to latest version broke dependency downloading 😓 https://github.com/coursier/coursier/issues/547

**Comment by mxl** [comment]
@ochrons Yep, such things happen sometimes 😄  As I remember I tested editor, etc. when I made this PR and everything seemed to work fine. Anyway if there is something I can help with - feel free to ask me.

**Comment by ochrons** [comment]
Yeah, this one was nasty because it depended on the contents of the Coursier cache directory. Took me some time to figure it out 😅

**Pull request closed without merging**
