### PR TITLE
Add Hamsters lib

### PR DESCRIPTION
**Pull request by loicdescotte**
Hamsters is a mini Scala utility library : https://github.com/scala-hamsters/hamsters

### CODE REVIEW

**Comment by loicdescotte** [comment]
Updated with last version of the lib

**Comment by ochrons** [comment]
Wouldn't the "Functional & type-level" group be more appropriate for this library?

Also the doc should just point to `scala-hamsters/hamsters`, since the repo main page contains installation information in addition to links to doc topics.

**Comment by loicdescotte** [comment]
Changes done, thanks :)

**Comment by ochrons** [comment]
Looking good! Two little things:
- the doc link should be just `"doc": "scala-hamsters/hamsters"` when referring to a github repo, ScalaFiddle will automatically expand it to full URL
- please squash the commits into one to keep repo history clean

Thanks!

**Comment by loicdescotte** [comment]
Done, doc link updated and only 1 commit is remaining :)
Thanks
Loïc

**Comment by loicdescotte** [comment]
Thanks for the merge!
I've tried to used it in scalafiddle and I have this error : 

```Library io.github.scala-hamsters %%% hamsters % 2.5.0 is not supported```

It occurs with both scala 2.11 and 2.12.

Is it a problem with the download of the lib ? 
The path in maven for the scala.js version is https://repo1.maven.org/maven2/io/github/scala-hamsters/hamsters_sjs0.6_2.12/2.5.0/

Thanks

Loïc

**Comment by ochrons** [comment]
The compilers just hadn't refreshed the libraries for some reason. I restarted them so now it seems to be there.

**Comment by loicdescotte** [comment]
Thanks it works!

**Pull request merged**
