### PR TITLE
Add Scalameta, Scalafix and Scalafmt to libraries.json

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by ochrons** [comment]
Just making sure that scalameta doesn't allow execution of user code on the server side as part of the compilation process?

**Comment by olafurpg** [comment]
Good question! Scalameta is just like any other library so it's not a problem. Today we changed our github description into  "Library to read, analyze, transform and generate Scala programs.", which hopefully clarifies what Scalameta can be used for.

**Comment by olafurpg** [comment]
Is there any way to test that the maven coordinates resolve? I just edited the json file.

**Comment by olafurpg** [comment]
Thanks a lot for merging! It's already live 😄 https://scalafiddle.io/sf/LZU8d7a/0

I'm looking forward to use the embedded mode to write our documentation

**Comment by olafurpg** [comment]
Whoops seems we have some linking errors in scalafix 😮  https://scalafiddle.io/sf/LZU8d7a/1 will need to fix this asap https://github.com/scalacenter/scalafix/issues/586

**Pull request merged**
