### PR TITLE
Update Monadless

### PR DESCRIPTION
**Pull request by fwbrasil**

### CODE REVIEW

**Comment by ochrons** [comment]
Are you sure there are no users of the previous version? If so, then it's fine to remove it, otherwise you should just add the new version.

**Comment by fwbrasil** [comment]
There aren't users of the previous version afaik, I think it's safe to merge.

**Comment by fwbrasil** [comment]
I've removed the old version because the artifact name also changed.

**Comment by ochrons** [comment]
Ok!

**Comment by ochrons** [comment]
This version is not published to Maven, so as a quick fix I removed monadless library altogether.

**Comment by fwbrasil** [comment]
@ochrons I do see the library on maven central:

2.11 http://search.maven.org/#artifactdetails%7Cio.monadless%7Cmonadless_2.11%7C0.0.12%7Cjar
2.12 http://search.maven.org/#artifactdetails%7Cio.monadless%7Cmonadless_2.12%7C0.0.12%7Cjar

**Comment by fwbrasil** [comment]
I see now, the scala.js version is not there. Sorry for the inconvenience, I'll fix it.

**Pull request merged**
