### PR TITLE
Fix for #52

### PR DESCRIPTION
**Pull request by thSoft**
Add OutWatch to libraries

### CODE REVIEW

**Comment by ochrons** [comment]
Scala 2.12 is not yet supported by ScalaFiddle, so you need to use 2.11 for libraries, too

**Comment by thSoft** [comment]
Fortunately OutWatch supports Scala 2.11 also: https://github.com/OutWatch/outwatch/blob/88604348470827d79007312e934f8df2b58d0a7b/build.sbt#L13

**Comment by ochrons** [comment]
Can you also squash the commits together to keep revision history clean, thanks!

**Comment by thSoft** [comment]
Thank you for merging! Unfortunately I specified the wrong organization, sorry. :( Should I open another PR for [fixing it](https://github.com/thSoft/scalafiddle-editor/commit/5dabf0ade20e5bb1ca08541de30e10b943235ffc)?

**Comment by ochrons** [comment]
Yea, please do :)

**Pull request merged**
