### PR TITLE
Add extraDeps for Binding.scala

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
This should close https://github.com/scalafiddle/scalafiddle-core/issues/10

**Review by ochrons — CHANGES_REQUESTED** [review]
You should not remove old versions, but add new ones, so that fiddles created with the previous version continue to work.

**Comment by Atry** [comment]
What if I want to change the artifact from `dom` to `binding`, and turn `dom` into an `extraDeps`?

**Comment by ochrons** [comment]
You can add deps to previous versions. I assume in this case the `dom` dep actually pulled in `binding` too? So it's ok to change the main dep to `binding` and then add `dom` as the extraDep.

**Comment by Atry** [comment]
Actually, `dom` depends on `binding`. Does that matter?

**Comment by ochrons** [comment]
It works as expected as this is just as you would do in SBT. You need to define the minimum set of libs and their deps are pulled in automatically.

**Comment by Atry** [comment]
Hi @ochrons , I have added 9.0.0 back. Could you review PR this again?

**Review by ochrons — CHANGES_REQUESTED** [review]
9.0.0 version has extraDeps with 9.0.2 version :)

**Comment by Atry** [comment]
@ochrons You are right.

Now I fixed it.

**Pull request merged**
