### PR TITLE
Add Binding.scala 9.0.3

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by ochrons** [comment]
Why the -M5 version? I'd rather have only final release versions listed in the public ScalaFiddle, unless there is some specific reason for an M or RC version.

**Comment by Atry** [comment]
OK, then

**Comment by Atry** [comment]
Hi @ochrons, I have deleted the `M` version. Could you merge this PR, please?

**Comment by ochrons** [comment]
LGTM

**Pull request merged**
