### PR TITLE
update Akka.Js to 1.2.5.9

### PR DESCRIPTION
**Pull request by andreaTP**
Updated Akka.Js and added Akka Typed.

### CODE REVIEW

**Comment by ochrons** [comment]
Is it really necessary to add both 1.2.5.8 and 1.2.5.9 versions?

**Comment by andreaTP** [comment]
Why not?

**Comment by andreaTP** [comment]
I mean it's not necessary obviously, but I do not see any reason for not doing it :-)

**Comment by ochrons** [comment]
The main reason is not to have versions of libraries available in ScalaFiddle that nobody is even using. The latest version is used by default, so having any older versions is typically only sensible when some existing fiddle is using it. Adding multiple versions at the time is therefore not that useful.

For Akka.js it might be different if the Akka documentation used different versions to match the library doc version, dunno if this is the case though.

**Comment by andreaTP** [comment]
fair enough updated the PR :-)

**Comment by andreaTP** [comment]
unfortunately I can't keep everything in sync with Akka documentation :-(
Akka and scalafiddle are both out of my hands and I have to rely on PR to get them working, not sure how I can do it better ...

**Pull request merged**
